#!/usr/bin/env python
from random import randint,choice,uniform
import random
from subprocess import call,Popen,PIPE
from string import ascii_lowercase
import os

solDir="solutions"
testDir="testcases"
progDir="CS12B032_HOME/Code"
execs="executables"

def gen_out(infile):
    noext=os.path.splitext(infile)[0]
    testPath= os.path.join(testDir,noext+".in")
    execPath=os.path.join(execs,noext)
    ansPath= os.path.join(solDir,noext+".ans")
    progPath= os.path.join(progDir,infile)
    sortPath= os.path.join(progDir,"q2_sort.c")
    # print progPath,ansPath,execPath,testPath
    if noext=='q1':
        os.system("gcc -o "+execPath+" "+progPath+" -lm")
    else:
        os.system("gcc -o "+execPath+" "+progPath+" "+sortPath+" -lm")

    with open(testPath,"r") as reader:
        with open(ansPath,"w") as writer:
            if noext=='q2' or noext=='q3':
                ps= Popen("./"+execPath, stdin= PIPE, stdout= PIPE, stderr= PIPE)
                out,err= ps.communicate(os.linesep.join([lines for lines in reader]))
                writer.write(out)
            else:
                lines= int(reader.readline())
                for i in range(lines):
                    ps=Popen("./"+execPath, stdin=PIPE,stdout=PIPE,stderr=PIPE)
                    lst=[reader.readline() for k in range(2)]
                    out,err=ps.communicate(os.linesep.join(lst))
                    writer.write(out)

def create3(infile):
    testfile=os.path.join(testDir,infile+".in")
    with open(testfile,"w") as w:
        w.write("10\n")
        for i in range(10):
            size= randint(1,50)
            w.write(str(size)+"\n")
            lst= [randint(-10**2,10**2) for k in range(size)]
            w.write(' '.join(map(str,lst))+"\n")
            w.write(' '.join(map(str,sorted(lst)))+"\n")
            w.write(' '.join(map(str,sorted(lst,reverse=True)))+"\n")

def create2(infile):
    testfile=os.path.join(testDir,infile+".in")
    with open(testfile,"w") as w:
        w.write("10\n")
        for i in range(10):
            size= randint(100,200)
            w.write(str(size)+"\n")
            w.write(' '.join(map(str,[randint(-10**3,10**3) for k in range(size)]))+"\n")


def create1(infile):
    testfile=os.path.join(testDir,infile+".in")
    with open(testfile,"w") as w:
        w.write("10\n")
        # first 5-testcases won't have more than 100 elements in them
        for i in range(10):
            size,k=randint(1,50),randint(1,10**2)
            w.write(str(size)+" "+str(k)+"\n")
            w.write(' '.join(map(str,[randint(0,k) for j in range(size)]))+"\n")


if __name__=='__main__':
        if not os.path.exists(solDir):
            os.system("mkdir "+solDir)
        if not os.path.exists(testDir):
            os.system("mkdir "+testDir)
        if not os.path.exists(execs):
            os.system("mkdir "+execs)
        # create1("q1")
        create2("q2")
        # create3("q3")
        # gen_out('q2.c')

