#!/usr/bin/env python
from random import randint,choice,uniform
import random
from subprocess import call,Popen,PIPE
from string import ascii_lowercase
import os

solDir="solutions"
testDir="testcases"
progDir="CS12B032_HOME/Code"
execs="executables"

def gen_out(infile):
    noext=os.path.splitext(infile)[0]
    testPath= os.path.join(testDir,noext+".in")
    execPath=os.path.join(execs,noext)
    ansPath= os.path.join(solDir,noext+".ans")
    progPath= os.path.join(progDir,infile)
    sortPath= os.path.join(progDir,"q2_sort.c")
    # print progPath,ansPath,execPath,testPath
    if noext=='q1':
        os.system("gcc -o "+execPath+" "+progPath+" -lm")
    else:
        os.system("gcc -o "+execPath+" "+progPath+" "+sortPath+" -lm")

    with open(testPath,"r") as reader:
        with open(ansPath,"w") as writer:
            if noext=='q2' or noext=='q3':
                ps= Popen("./"+execPath, stdin= PIPE, stdout= PIPE, stderr= PIPE)
                out,err= ps.communicate(os.linesep.join([lines for lines in reader]))
                writer.write(out)
            else:
                lines= int(reader.readline())
                for i in range(lines):
                    ps=Popen("./"+execPath, stdin=PIPE,stdout=PIPE,stderr=PIPE)
                    lst=[reader.readline() for k in range(2)]
                    out,err=ps.communicate(os.linesep.join(lst))
                    writer.write(out)

def create1(infile):
    testfile=os.path.join(testDir,infile+".in")
    with open(testfile,"w") as w:
        w.write("20\n")
        lst2=["[","]","(",")","{","}"]
        for i in range(20):
            str_len=randint(100,1000)
            lst=[lst2[randint(0,5)] for j in range(str_len)]
            w.write(''.join(lst)+"\n")


def create2(infile):
    testfile=os.path.join(testDir,infile+".in")
    with open(testfile,"w") as w:
        w.write("20\n")
        lst2=["{","}"]
        for i in range(20):
            str_len=randint(1,1000)
            lst=[lst2[randint(0,1)] for j in range(str_len)]
            w.write(''.join(lst)+"\n")


def create3(infile):
    testfile=os.path.join(testDir,infile+".in")
    with open(testfile,"w") as w:
        w.write("20\n")
        for i in range(20):
            arr_size=randint(10,1000)
            lst=[randint(-1000,1000) for j in range(arr_size)]
            w.write(str(arr_size)+"\n")
            w.write(' '.join(map(str,lst))+"\n")


if __name__=='__main__':
    if not os.path.exists(solDir):
        os.system("mkdir "+solDir)
    if not os.path.exists(testDir):
        os.system("mkdir "+testDir)
    if not os.path.exists(execs):
        os.system("mkdir "+execs)
    create3("q3")
    # create2("q2")
    # create1("q1")

